services:
  - type: web
    name: emi-marketplace-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000